Bugfix: Shutting down pigeon resulted in runtime error
when calling !bb the following exception occured:

Exception in thread "pool-1-thread-2"
org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `map' for nil:NilClass
at RUBY.all(/Users/simplay/repos/pigeon/src/user.rb:15)
at RUBY.find_by_nick(/Users/simplay/repos/pigeon/src/user.rb:41)
at RUBY.block in attach_listeners(/Users/simplay/repos/pigeon/src/bot.rb:79)`

This was due to the bot's event listener that was still running even
though the server connection was already closed. by checkecking whether
the server is still running, we can ignore later thrown events.